FROM confluent/kafka:0.10.0.0-cp1
MAINTAINER team-usjanus <us-janus@fundingcircle.com>

USER root
RUN apt-get update \
    && apt-get install -y uuid-runtime vim-nox \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /var/tmp/*

COPY docker/.bashrc /root

ENTRYPOINT ["/bin/bash"]
