run-name: Jackdaw build
on:
  workflow_call:
    inputs:
      foo:
        default: "thing"
        type: string
jobs:
  run-tests:
    runs-on: ubuntu-latest
    container: clojure:latest
    environment: test
  - name: deploy_snapshot
    env:
      CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
      CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
      GPG_PRIVATE_KEY:  ${{ secrets.GPG_PRIVATE_KEY }}
    run: |
       apt-get update
       apt-get -y install gnupg
       echo $GPG_PRIVATE_KEY |base64 --decode |gpg --yes --batch --import
       gpg --list-keys
       lein do jar, pom, deploy clojars

  