run-name: Jackdaw build

on:
  workflow_call:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    container: clojure:latest
    environment: test
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 100
      - name: deploy_snapshot
        env:
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
        run: |
          git config --global --add safe.directory /__w/jackdaw/jackdaw
          lein do jar, pom, deploy clojars
