run-name: Jackdaw build
on:
  push:
    branches-ignore:
      - master
      - main
jobs:
  environment: test
  run-tests:
    uses: ./.github/workflows/run-tests.yaml
  deploy:
    uses: ./.github/workflows/deploy.yaml


# cache
# deploy main
# safe dir
# clone depth