run-name: Jackdaw build
on:
  workflow_call:
    inputs:
      foo:
        default: "thing"
        type: string
jobs:
  run-tests:
    runs-on: ubuntu-latest
    container: clojure:latest
    environment: test
    steps:
      - name: deploy_snapshot
        env:
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
          GPG_PRIVATE_KEY:  ${{ secrets.GPG_PRIVATE_KEY }}
        run: |
          lein do jar, pom, deploy clojars
