run-name: Jackdaw build

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '*publish-snapshot*'

jobs:
  run_checks:
    uses: ./.github/workflows/run_checks.yaml
  deploy:
    needs: run_checks
    runs-on: ubuntu-latest
    container: 
      image: clojure:latest
    environment: test
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: deploy
        env:
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        run: |
          apt-get update
          apt-get install -y gpg 
          echo $GPG_PRIVATE_KEY |base64 --decode |gpg --yes --batch --import
          export LEIN_GPG=/__w/jackdaw/jackdaw/bin/gpg
          export REAL_GPG=$(which gpg)
          su - 1001
          lein do jar, pom, deploy clojars

