run-name: Jackdaw build
on:
  push:
    branches-ignore:
      - master
      - main
jobs:
  run-checks:
    uses: ./.github/workflows/run-checks.yaml
  deploy:
    uses: ./.github/workflows/deploy.yaml
    # needs: run-tests

# cache
# deploy main
# safe dir
# clone depth