run-name: Jackdaw build
on:
  push:
    branches-ignore:
      - master
      - main
jobs:
  run-tests:
    uses: ./.github/workflows/run-tests.yaml
  deploy:
    uses: ./.github/workflows/deploy.yaml
    needs: run-tests

# cache
# deploy main
# safe dir
# clone depth