run-name: Run checks

on:
  workflow_call:

jobs:
  RunChecks:
    runs-on: ubuntu-latest
    container: 
      image:  clojure:latest
      options: --user 1001 # don't run as root
    services:
      kafka:
        image: apache/kafka:3.7.0
        env:
          CLUSTER_ID: 8L6g2nShT-eMCtK--X46sw
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
          KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
          KAFKA_BROKER_ID: 1
          KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
          KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
          KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
          KAFKA_LISTENERS: CONTROLLER://:29093,PLAINTEXT://:9092
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
          KAFKA_PROCESS_ROLES: broker,controller
          KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
          KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      schema-registry:
        image: confluentinc/cp-schema-registry:7.6.0
        env:
          SCHEMA_REGISTRY_HOST_NAME: schema-registry
          SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka:9092
          SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081
      kafka-rest:
        image: confluentinc/cp-kafka-rest:7.6.0
        env:
          KAFKA_REST_BOOTSTRAP_SERVERS: kafka:9092
          KAFKA_REST_HOST_NAME: kafka-rest
          KAFKA_REST_LISTENERS: http://0.0.0.0:8082
          KAFKA_REST_SCHEMA_REGISTRY_URL: http://schema-registry:8081
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          # do not fetch tags if the trigger event is a tag push
          fetch-tags: ${{ startsWith(github.ref, 'refs/tags') != true }}
          fetch-depth: 100
      - name: build
        run: | 
          lein kaocha
        env: 
          KAFKA_BOOTSTRAP_SERVERS: kafka
          SCHEMA_REGISTRY_HOST: schema-registry
          KAFKA_REST_PROXY_HOST: kafka-rest
      - name: lint
        run: lein clj-kondo --lint src test || true
