run-name: Run checks

on:
  workflow_call:

jobs:
  RunChecks:
    runs-on: ubuntu-latest
    container: 
      image:  clojure:latest
      options: --user 1001 # don't run as root
    services:
      kafka:
        image: confluentinc/cp-kafka:5.1.3
        env:
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
          KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
          KAFKA_BROKER_ID: 1
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
          KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
          KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
          KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      schema-registry:
        image: confluentinc/cp-schema-registry:5.1.2
        env:
          SCHEMA_REGISTRY_HOST_NAME: schema-registry
          SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'
      kafka-rest:
        image: confluentinc/cp-kafka-rest:6.1.1
        env:
          KAFKA_REST_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_REST_BOOTSTRAP_SERVERS: kafka:9092
          KAFKA_REST_LISTENERS: http://0.0.0.0:8082
          KAFKA_REST_SCHEMA_REGISTRY: http://schema-registry:8081
          KAFKA_REST_HOST_NAME: kafka-rest
      zookeeper:
        image: confluentinc/cp-zookeeper:5.1.3
        env: 
          ZOOKEEPER_CLIENT_PORT: 2181
          ZOOKEEPER_TICK_TIME: 2000
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          # do not fetch tags if the trigger event is a tag push
          fetch-tags: ${{ startsWith(github.ref, 'refs/tags') != true }}
          fetch-depth: 100
      - name: build
        run: | 
          lein kaocha
        env: 
          KAFKA_BOOTSTRAP_SERVERS: kafka
          ZOOKEEPER_HOST: zoopkeeper
          SCHEMA_REGISTRY_HOST: schema-registry
          KAFKA_REST_PROXY_HOST: kafka-rest
      - name: lint
        run: lein clj-kondo --lint src test || true
